version: '2'
services:
  arcam_api:
    container_name: arcam_api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    command:
      - --arcam_ip=$ARCAM_IP
    restart: 'on-failure'
  arcam_nginx:
    container_name: arcam_nginx
    build:
      context: ./website
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    restart: 'on-failure'
    depends_on:
      - arcam_api
