version: '2'
services:
  arcam-remote-website:
    container_name: arcam-remote-website
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HOST_IP=192.168.1.4
    restart: 'on-failure'
  nginx:
    image: 'nginx'
    container_name: arcam_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    restart: 'on-failure'
    depends_on:
      - arcam-remote-website

volumes:
  grafana:
  prometheus:
  alertmanager-data:
