version: '2'
services:
  arcam-remote-website:
    container_name: arcam-remote-website
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HOST_IP=192.168.1.4
    restart: 'on-failure'
  prometheus:
    image: prom/prometheus:latest
    container_name: arcam_prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - cadvisor

  cadvisor:
    image: braingamer/cadvisor-arm:latest
    # for running on x86:
    # image: gcr.io/cadvisor/cadvisor:latest
    container_name: arcam_cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - arcam-remote-website

  grafana:
    image: grafana/grafana:latest
    container_name: arcam_grafana
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    user: "1000"
    depends_on:
      - prometheus
  nginx:
    image: 'nginx'
    container_name: arcam_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    restart: 'on-failure'
    depends_on:
      - arcam-remote-website

volumes:
  grafana:
  prometheus:
