version: '2'
services:
  arcam-remote-website:
    container_name: arcam-remote-website
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - HOST_IP=192.168.1.4
    restart: 'on-failure'
    networks:
      - arcam-remote-local
  nginx:
    image: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    restart: 'on-failure'
    depends_on:
      - arcam-remote-website
    networks:
      - arcam-remote-local

networks:
  arcam-remote-local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.68.0.0/24
          gateway: 172.68.0.254
