global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: arcam-remote-website
    static_configs:
      - targets: ["arcam-remote-website:50052",]
